### ISSUE TITLE
Don't log plex token

### ISSUE THREAD

**Issue by 0dragosh** [RemiRigal/Plex-Auto-Languages#1]
Upon launch, the app spits out the plex token in plain text. It would be great if it didn't do that, for obvious security reasons.

```[INFO] Setting value of parameter PLEX_TOKEN to 'xxxxxxxxxxx' from environment variable```

**Comment by dphildebrandt** [comment]
Would also be great if the docker supported the plex token as a docker secret.

**Comment by RemiRigal** [comment]
You are absolutely right, it needs to be fixed, thank you for opening an issue !

**Comment by RemiRigal** [comment]
Fixed by [ae8725b](https://github.com/RemiRigal/Plex-Auto-Languages/commit/ae8725bac4e38b06ed9089eb7356e982f1cd9e49) and released in v1.0.2.
The values of all parameters are no longer displayed.

**Comment by RemiRigal** [comment]
@dphildebrandt I just wanted to let you know that you can now use a Docker secret named `plex_token` to set the Plex Token. The feature is available from version v1.0.4.
