### ISSUE TITLE
PAL caching subtitle streams issue

### ISSUE THREAD

**Issue by dekaidekai** [RemiRigal/Plex-Auto-Languages#109]
I might be wrong on how PAL is supposed to behave, but I believe how PAL caches streams to ensure that it does not need to update future episodes again when users play the episodes again might be causing some issues when switching back and forth between languages.

### Example flow of reproducing the issue
(you can pick any two different languages to test this out)

1. Start PAL container fresh with no cache and empty [plex.cache.default_streams](https://github.com/RemiRigal/Plex-Auto-Languages/blob/d08a88aed67329f4388309a5c88ab55433fd5fb4/plex_auto_languages/plex_server_cache.py#L29).
2. Open show's first episode, setting subtitles language to `Arabic`
  a. This will [cache](https://github.com/RemiRigal/Plex-Auto-Languages/blob/d08a88aed67329f4388309a5c88ab55433fd5fb4/plex_auto_languages/alerts/playing.py#L81) this episode's stream to dict key and value `/library/metadata/25911: (155623, 155627)`.
  b. All future episodes are set to be `Arabic`. Thanks PAL!
3. Actually...nvm I want the show subtitles to be in Japanese. 
4. Open show's first episode again, setting subtitles language to `Japanese`
  a. PAL will check [here](https://github.com/RemiRigal/Plex-Auto-Languages/blob/d08a88aed67329f4388309a5c88ab55433fd5fb4/plex_auto_languages/alerts/playing.py#L79), is the episode's stream the same as the cached one? No it's not since it's now Japanese and a different value; `/library/metadata/25911: (155623, 155641)`, so PAL continues to change the show's subtitles!
  b. ❗ PAL will NOT cache this new set `Japanese` stream for this episode [here](https://github.com/RemiRigal/Plex-Auto-Languages/blob/d08a88aed67329f4388309a5c88ab55433fd5fb4/plex_auto_languages/alerts/playing.py#L81). Because we use the method [setdefault](https://www.w3schools.com/python/ref_dictionary_setdefault.asp), which if a key is already set in a dict, will not override it's value. Since we already set this episode key in step 2a., then the cache will not be overridden, and the cached value for this episode stream is still `Arabic`; `/library/metadata/25911: (155623, 155627)`. 
  c. Even though it didn't cache to `Japanese`, PAL code continues and all future episodes subtitles are set to be `Japanese`. Thanks PAL!
5. Actually...nvm again! I want the show subtitles to be in Arabic again. 
6. Open show's first episode, setting subtitles language back to `Arabic`
  a.  ❗ Again, PAL will check [here](https://github.com/RemiRigal/Plex-Auto-Languages/blob/d08a88aed67329f4388309a5c88ab55433fd5fb4/plex_auto_languages/alerts/playing.py#L79), is the episode's stream the same as the cached one? Well, since we never updated the cache to be `Japanese`, the cached value is still `Arabic`; `/library/metadata/25911: (155623, 155627)`, and it thinks the stream is unchanged, and returns early!
  b. ❗PAL will NOT set any of the future episodes subtitles language to `Arabic`.

This essentially means since the cache has the langauge `Arabic` stream value stuck in it for this episode and it cannot be updated, we can't switch the show's subtitles back to Arabic, unless we recreate the container and wipe the cache.

### Proposed fix:
I think the issue is when we cache the episode's stream value [here](https://github.com/RemiRigal/Plex-Auto-Languages/blob/d08a88aed67329f4388309a5c88ab55433fd5fb4/plex_auto_languages/alerts/playing.py#L81). We use [setdefault](https://www.w3schools.com/python/ref_dictionary_setdefault.asp) instead of a method that should always override the cached value like:

replace [this line](https://github.com/RemiRigal/Plex-Auto-Languages/blob/d08a88aed67329f4388309a5c88ab55433fd5fb4/plex_auto_languages/alerts/playing.py#L81) with:
```
plex.cache.default_streams[item.key] = pair_id
```

**Comment by dekaidekai** [comment]
cc @JourneyOver

**Comment by JourneyOver** [comment]
Hmm this bug seems to only be an issue when the `update_strategy` is set specifically to `next` instead of `all` as I did a test running through your example flow above with my config file which had it set to `all` and I wasn't experiencing this issue, so decided to do the test again with it set to `next` and ran straight into the issue of it not switching the subtitle language back.

I'll do a quick test with the proposed fix to see if it affects the `update_strategy` any when switching between the two different settings and if it doesn't then I'll push up the changes so you can test and see if everything is working correctly on your end and then we can call this fixed or not depending on things.

**Comment by JourneyOver** [comment]
Have pushed up a new build (which should be done building here shortly) with the proposed change, I did a small test beforehand and it didn't seem to cause any adverse affects, but feel free to test and confirm/deny if everything is working okay on your end.

I've also gone ahead and allowed issues over on my [repository](https://github.com/JourneyDocker/Plex-Auto-Languages/issues) now as well.

**Comment by dekaidekai** [comment]
@JourneyOver Good point I forgot to mention I was in `next` strategy! I'll test the both modes as well.

Thanks as always for these quick fixes 💯

**Comment by JourneyOver** [comment]
It's all good :P thankfully I remembered that some of my settings are different than the default settings, so I decided to check it out with default settings which for sure ran into the issue.

And it's not a problem, gotta thank you for the proposed code changes as well as it makes getting these fixes out quickly :)
