### ISSUE TITLE
PAL crashing when setting subtitles to OFF

### ISSUE THREAD

**Issue by dekaidekai** [RemiRigal/Plex-Auto-Languages#110]
If you set an episode's subtitles to `off`, I believe it crashes:
```
Traceback (most recent call last):
  File "/app/plex_auto_languages/plex_alert_handler.py", line 66, in _process_alerts
    alert.process(self._plex)
    ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/app/plex_auto_languages/alerts/playing.py", line 85, in process
    plex.change_tracks(username, item, EventType.PLAY_OR_ACTIVITY)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plex_auto_languages/plex_server.py", line 256, in change_tracks
    track_changes.compute(episodes)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/app/plex_auto_languages/track_changes.py", line 85, in compute
    matching_subtitle_stream = self._match_subtitle_stream(part.subtitleStreams())
  File "/app/plex_auto_languages/track_changes.py", line 208, in _match_subtitle_stream
    if self._subtitle_stream.forced == stream.forced:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'forced'
```

I think because it is expected [here](https://github.com/RemiRigal/Plex-Auto-Languages/blob/d08a88aed67329f4388309a5c88ab55433fd5fb4/plex_auto_languages/track_changes.py#L181) that `self._subtitle_stream`, which is the currently selected subtitle stream, to be not `None`, but it is if we set the subtitles to be off.

We need to find a way to handle when subtitles are turned off, and set all future episodes to turn off subtitles.

**Comment by JourneyOver** [comment]
This one I haven't ran into myself specifically at all. btw don't forget that I had opened up the issues page on my own repo as well which might be a better place to do all this since fixes and everything are mostly coming in on my repo now.

**Comment by dekaidekai** [comment]
@JourneyOver Woops sorry I'll move this there!

**Comment by dekaidekai** [comment]
moved to here
https://github.com/JourneyDocker/Plex-Auto-Languages/issues/1
