### ISSUE TITLE
Notifications Showing `None` for User

### ISSUE THREAD

**Issue by angrycuban13** [RemiRigal/Plex-Auto-Languages#24]
I have notifications set up and they seem to be working correctly. Except, whenever one of my home users (not managed) starts watching a show the notification looks as follows:

```
PlexAutoLanguages - Futurama
Show: Futurama
User: None
Audio: English (EAC3 Stereo)
Subtitles: English (SRT)
Updated episodes: 1/124 (S01E01 - S07E26)
```

**Comment by RemiRigal** [comment]
Can you confirm that this behavior happens when one of your home user is watching something and not during scheduler tasks ? You should be able to tell by looking at the logs.

I'm asking this because the scheduler tasks sometimes have issues with getting the associated user. I'm currently working on it.

**Comment by angrycuban13** [comment]
It is during the scheduled task, sorry I didn't specify this in the initial issue. 

I haven't really been getting notifications "live" the last few days. They worked back when you first posted in Reddit but after the last few updates I only seem to get notifications during the scheduled task. I'll post my config here in a bit

**Comment by RemiRigal** [comment]
The latest version (v1.0.14) should solve the issue of the user being `None` during the scheduler task. Can you update and let me know if it works ?

> I haven't really been getting notifications "live" the last few days. They worked back when you first posted in Reddit but after the last few updates I only seem to get notifications during the scheduled task.

Is there anything relevant in the logs ? Have you tried restarting the container ?

**Comment by angrycuban13** [comment]
When I went to check it this morning I saw it had a `connection refused` and a `401` error so maybe it has been sitting like that for the last few days. I pulled but it seems like I have the latest version, I'll give it another pull later today just in case.

I enabled `debug` in my config and will keep an eye on it.

**Comment by RemiRigal** [comment]
Could you give me the full log for the error `401` you got ? Thank you !

**Comment by angrycuban13** [comment]
I haven't poked around but do you have a way for the logs to be accessible by the hosts? Right now, I only have container logs on the console.

**Comment by angrycuban13** [comment]
Here are the container logs

https://0bin.net/paste/qN3G2hSO#kYrkcmZPP8BEJs-+DBfsJtBjKkGWPPL984dFI3DfNFt

**Comment by RemiRigal** [comment]
Since you are using a valid Plex token for the admin user (id: 1), I'm a bit surprised by the `401: Unauthorized` error. If you experience this again, can you open a new issue ?

Did the `connection refused` happened during a Plex restart ? I get the same type of error when starting PlexAutoLanguages while Plex is stopped.

**Comment by angrycuban13** [comment]
Hmm that's an interesting theory. Maybe it happened when Plex was doing an update or something. I would have expected something other than a 401 though. If I see it again I'll be sure to open a new one. 

By the way, we can close this one. Scheduled task is working. 

```
PlexAutoLanguages - Futurama
Show: Futurama
User: myuser
Audio: English (EAC3 Stereo)
Subtitles: English (SRT)
Updated episodes: 1/124 (S01E01 - S07E26)
```
