### ISSUE TITLE
[Feature Request] More flexibility for which notifications are sent

### ISSUE THREAD

**Issue by rg9400** [RemiRigal/Plex-Auto-Languages#36]
Right now, while you can choose which users to get notifications for, it will still send notifications in any event that PAL modifies languages/subs. This means that if it is watching for new episodes or file changes, any such event will trigger PAL which will then send a condensed notification that the episode was changed for all users. This isn't particularly useful and creates a lot of noise.

Ideally, there is a way to subscribe to only "active" triggers, e.g. plays or I guess any activity if so configured for the user. I would also want notifications for changes made during the scheduled run if enabled, but you could bifurcate those out if you want more flexibility as well. But from my usecase, the main goal is to suppress the new episode/file change notifications

Thanks!

**Comment by RemiRigal** [comment]
Implemented in #37, see the PR or the [README](https://github.com/RemiRigal/Plex-Auto-Languages/blob/master/README.md) for more details about the implementation and how to use it.

The changes have been merged and released in version `v1.1.1`. Let me know if it fits your needs !

**Comment by rg9400** [comment]
This is working, thanks a ton! Closing the issue
