### ISSUE TITLE
Silently Crashes During Scanning

### ISSUE THREAD

**Issue by dcplaya** [RemiRigal/Plex-Auto-Languages#50]
I just discovered this! I set it up to run in my k8s cluster, but it seems to be silently crashing. I have enabled debug mode, below is the log.

```
[#0099ff-::]2022-07-17 06:38:55,349 [INFO] Parsing config file '/config/config.yaml'
[#0099ff-::]2022-07-17 06:38:55,354 [INFO] Setting value of parameter PLEX_URL from environment variable
[#0099ff-::]2022-07-17 06:38:55,354 [INFO] Setting value of parameter PLEX_TOKEN from environment variable
[#0099ff-::]2022-07-17 06:38:55,354 [INFO] The provided configuration has been successfully validated
2022-07-17 06:38:55,354 [DEBUG] Debug mode enabled
[#0099ff-::]2022-07-17 06:38:55,355 [INFO] Starting scheduler
[#0099ff-::]2022-07-17 06:38:55,934 [INFO] Successfully connected as user 'PLEX_USERNAME' (id: 1)
[#0099ff-::]2022-07-17 06:38:55,934 [INFO] Scanning all episodes from the Plex library, this action should only take a few seconds but can take several minutes for larger libraries 
2022-07-17 06:38:55,934 [DEBUG] [Cache] Refreshing library cache 
Stream closed EOF for media/plex-auto-languages-7b9f58948d-hqjpl (plex-auto-languages)  
```

Im not even sure where to start debugging. I was hoping enabling debug mode would give me a lot more info, but it does not.
I am running version `1.1.3` container image

Any suggestions?

**Comment by dcplaya** [comment]
I feel like a dummy....
I limited the max memory to 1G and it kept crashing due to OOM. 

I bumped it to 4G and its running fine now.

**Comment by RemiRigal** [comment]
Hi @dcplaya ! Happy to see that you solved your issue, your feedback is very important as others might experience this too. Thank you for opening an issue, let me know if you encounter any difficulties.
