### ISSUE TITLE
Docker image compatible with Rasperry Pi (arm) 32bits and 64bits

### ISSUE THREAD

**Issue by HydrelioxGitHub** [RemiRigal/Plex-Auto-Languages#55]
All is in the title. I'm running docker on a rpi with raspianOS 64bits version. I've seen on the DockerHub there is only amd64 images. Is-it difficult to provide such an image (I'm a noob on docker so I don't how much work it represents) ?

Thank you for your time and your work.

**Comment by RemiRigal** [comment]
Thank you for your suggestion. I've added `linux/arm64` and `linux/arm/v7` images on the master branch.

For now they are only available for the `remirigal/plex-auto-languages:master` images, the `remirigal/plex-auto-languages:latest` arm-based images will be available as soon as a new version is released. I will let you know.

**Comment by RemiRigal** [comment]
Version `v1.2.0` has been released as well as the new arm-based images for `remirigal/plex-auto-languages:latest`.

I'm closing this issue but feel free to reopen it if you have any question.
