### ISSUE TITLE
ConnectionError: Unable to connect to plex server, retrying...

### ISSUE THREAD

**Issue by XzadikDev** [RemiRigal/Plex-Auto-Languages#66]
Tried both http://IP:32400 and http://nas_url:32400 but issue persist. Any ideas on what I didn't set up correctly that's causing this issue?

**Comment by Peccadilloz** [comment]
Have the same issue. Running in a docker container in the same machine as Plex. At first it works fine and then after an hour it only sends this error for all users until the server is restarted.

**Comment by RemiRigal** [comment]
Hello @XzadikDev, could you give me additional information on your setup please ? Are you running Plex-Auto-Languages with docker or natively with Python ? Is Plex running on the same machine ? What OS are you using ?
Thank you !
