### ISSUE TITLE
Scheduler Error in UnRaid Docker

### ISSUE THREAD

**Issue by shomilsaini** [RemiRigal/Plex-Auto-Languages#90]
```
2023-08-20 02:00:00,826 [INFO] Starting scheduler task
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/app/plex_auto_languages/utils/scheduler.py", line 22, in run
    schedule.run_pending()
  File "/usr/local/lib/python3.8/site-packages/schedule/__init__.py", line 822, in run_pending
    default_scheduler.run_pending()
  File "/usr/local/lib/python3.8/site-packages/schedule/__init__.py", line 100, in run_pending
    self._run_job(job)
  File "/usr/local/lib/python3.8/site-packages/schedule/__init__.py", line 172, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.8/site-packages/schedule/__init__.py", line 693, in run
    ret = self.job_func()
  File "main.py", line 107, in scheduler_callback
    self.plex.start_deep_analysis()
  File "/app/plex_auto_languages/plex_server.py", line 283, in start_deep_analysis
    episode.reload()
  File "/usr/local/lib/python3.8/site-packages/plexapi/base.py", line 394, in reload
    return self._reload(key=key, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/plexapi/base.py", line 952, in _reload
    raise NotImplementedError('History objects cannot be reloaded. Use source() to get the source media item.')
NotImplementedError: History objects cannot be reloaded. Use source() to get the source media item.
```

**Comment by nwicone** [comment]
I have the exact same issue

**Comment by foostuff** [comment]
Same for me in a proxmox docker.

**Comment by nwicone** [comment]
> Same for me in a proxmox docker.

Can you share your docker config ?
I will check if you've set everything correctly.

**Comment by foostuff** [comment]
sure. my env is here: https://pastebin.com/uNNVbtw1
I pasted the minimal configuration into portainer: https://github.com/RemiRigal/Plex-Auto-Languages#docker-compose-minimal-configuration

**Comment by nwicone** [comment]
> sure. my env is here: https://pastebin.com/uNNVbtw1 I pasted the minimal configuration into portainer: https://github.com/RemiRigal/Plex-Auto-Languages#docker-compose-minimal-configuration

Thank you, I don't see any problem of configuration.
When it happened to me, I just had to restart the app

**Comment by bakerboy448** [comment]
Not specific to unraid, seeing this in docker on 22.04

**Comment by JourneyOver** [comment]
Same as bakerboy, just started using this as of last night and went to go check on some docker stuff today and noticed this error in `plexautolanguages` logs.

**Comment by LightSeek3r** [comment]
Same error with Docker on Windows 11

**Comment by LightSeek3r** [comment]
Still seeing this with Docker on Windows 11. At every single run. Incrementally, over days, it causes instabilities in Docker. 
![image](https://github.com/RemiRigal/Plex-Auto-Languages/assets/75648597/e064636b-7d52-44b9-82d9-45f080063f56)

**Comment by ChristianMalazarte** [comment]
I have a script that restarts Plex Auto Languages every 6 hours lol.

**Comment by LightSeek3r** [comment]
If resolving that bug is too hard, at least could we have a way not to have this scheduler activated? External scripts to restart the whole thing because it crashed is at best a temporary mitigation solution, not an okay thing in software development

**Comment by ChristianMalazarte** [comment]
> If resolving that bug is too hard, at least could we have a way not to have this scheduler activated? External scripts to restart the whole thing because it crashed is at best a temporary mitigation solution, not an okay thing in software development

The developer has been AWOL for a long time now so good luck.

**Comment by michaeljh9** [comment]
I am aware this is meant to be a Docker-centric thread. I'm running it on bare metal fully up-to-date Debian 12.5.
I setup the script yesterday. I left it running overnight. I woke up in the morning to see the scheduler crashed. It was still running in the terminal but I wasn't sure if the script was still running sufficiently despite the crash.

What is the purpose of the scheduler? The script appeared to be working as intended without it.
![crash](https://github.com/RemiRigal/Plex-Auto-Languages/assets/13524815/4319b1fd-af48-4f46-a9ea-c1236e2d3d41)

**Comment by Whereamnow** [comment]
> I am aware this is meant to be a Docker-centric thread. I'm running it on bare metal, fully up-to-date Debian 12.5. I setup the script yesterday. I left it running overnight. I woke up to see the scheduler crashed. It was still running in the terminal but I wasn't sure if the script was still running sufficiently despite the crash.
> 
> What is the purpose of the scheduler? The script appeared to be working as intended without it.
> 
> To the author or any active people, I'm willing to provide any info I can to facilitate a fix.
> 
> ![crash](https://private-user-images.githubusercontent.com/13524815/340335427-4319b1fd-af48-4f46-a9ea-c1236e2d3d41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMTg3OTAsIm5iZiI6MTcyMDIxODQ5MCwicGF0aCI6Ii8xMzUyNDgxNS8zNDAzMzU0MjctNDMxOWIxZmQtYWY0OC00ZjQ2LWE5ZWEtYzEyMzZlMmQzZDQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDIyMjgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZmY1MWM2MjkyNDM4ODZhY2Y5NzgyMTNhMDU4NTgyYjcyMDVlZjIxM2YyYjgyNTI3OWE2YzZhZDkyNGQ1MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QYX-Ta7-scV5efpwYA6lLhAJ0VA_IK_aca0uvUFilpU)

  scheduler:
    # Whether of not to enable the scheduler, defaults to 'true'
    # The scheduler will perform a deeper analysis of all recently played TV Shows
    enable: false

**Comment by shomilsaini** [comment]
> > I am aware this is meant to be a Docker-centric thread. I'm running it on bare metal, fully up-to-date Debian 12.5. I setup the script yesterday. I left it running overnight. I woke up to see the scheduler crashed. It was still running in the terminal but I wasn't sure if the script was still running sufficiently despite the crash.
> > What is the purpose of the scheduler? The script appeared to be working as intended without it.
> > To the author or any active people, I'm willing to provide any info I can to facilitate a fix.
> > ![crash](https://private-user-images.githubusercontent.com/13524815/340335427-4319b1fd-af48-4f46-a9ea-c1236e2d3d41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMTg3OTAsIm5iZiI6MTcyMDIxODQ5MCwicGF0aCI6Ii8xMzUyNDgxNS8zNDAzMzU0MjctNDMxOWIxZmQtYWY0OC00ZjQ2LWE5ZWEtYzEyMzZlMmQzZDQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDIyMjgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZmY1MWM2MjkyNDM4ODZhY2Y5NzgyMTNhMDU4NTgyYjcyMDVlZjIxM2YyYjgyNTI3OWE2YzZhZDkyNGQ1MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QYX-Ta7-scV5efpwYA6lLhAJ0VA_IK_aca0uvUFilpU)
> 
> scheduler: # Whether of not to enable the scheduler, defaults to 'true' # The scheduler will perform a deeper analysis of all recently played TV Shows enable: false

Where is this setting to toggle scheduler off? I am running on UnRaid as Docker container.

Thanks

**Comment by shomilsaini** [comment]
So, mapped default.yaml from host to container as follows:
map container - `/app/config` to host - `/mnt/user/appdata/plex-auto-languages/config`

Here is the file contents if anyone is interested:
```
plexautolanguages:
  update_level: "show"
  update_strategy: "next"
  trigger_on_play: true
  trigger_on_scan: true
  trigger_on_activity: false
  refresh_library_on_scan: true
  ignore_tags:
    - PAL_IGNORE

  plex:
    url: ""
    token: ""

  scheduler:
    enable: false
    schedule_time: "02:00"

  notifications:
    enable: false
    apprise_configs: []

  debug: false
```

Closing the issue as dev is not responding and this is the best I can find for now.

Thanks everyone!
